/* ON CREE LA BASE DE DONNEES / AU PREALABLE ON VERIFIE QU'ELLE N'EST PAS DEJA EXISTANTE */
CREATE DATABASE IF NOT EXISTS theaterDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

/* ON SELECTIONNE ENSUITE LA DATABASE theaterDB */
USE theaterDB;


/* ON CREE LES DIFFERENTES TABLES / ON VERIFIE AU PREALABLE QU'ELLES N'EXISTENT PAS */

CREATE TABLE IF NOT EXISTS theater_complex (
  complex_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  complex_name VARCHAR(60) NOT NULL
) engine=INNODB;

CREATE TABLE IF NOT EXISTS theater (
  theater_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  theater_name VARCHAR(30) NOT NULL,
  theater_address VARCHAR(60),
  theater_postal_code INTEGER(5),
  theater_city VARCHAR(60),
  complex_id INTEGER,
  FOREIGN KEY (complex_id)
    REFERENCES theater_complex(complex_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) engine=INNODB;

CREATE TABLE IF NOT EXISTS room (
  room_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  room_number INTEGER NOT NULL,
  room_seats INTEGER NOT NULL,
  theater_id INTEGER NOT NULL,
  FOREIGN KEY (theater_id)
    REFERENCES theater(theater_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) engine=INNODB;

CREATE TABLE IF NOT EXISTS film (
  film_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  film_title VARCHAR(60) NOT NULL,
  film_year INTEGER (4) NOT NULL,
  film_length INTEGER NOT NULL
) engine=INNODB;

CREATE TABLE IF NOT EXISTS event (
  event_id INTEGER AUTO_INCREMENT NOT NULL UNIQUE, 
  event_date DATETIME NOT NULL,
  room_id INTEGER NOT NULL,
  film_id INTEGER NOT NULL,
  FOREIGN KEY (room_id)
    REFERENCES room(room_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (film_id)
    REFERENCES film(film_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  PRIMARY KEY(event_date, room_id)
) engine=INNODB;

CREATE TABLE IF NOT EXISTS client (
  client_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  client_fn VARCHAR(60) NOT NULL,
  client_ln VARCHAR(60) NOT NULL,
  client_email VARCHAR(60) NOT NULL,
  client_password VARCHAR(60) NOT NULL
) engine=INNODB;

CREATE TABLE IF NOT EXISTS price(
  price_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  price_value FLOAT(4,2) NOT NULL,
  price_name VARCHAR(30) NOT NULL
) engine=INNODB;

CREATE TABLE IF NOT EXISTS ticket(
  ticket_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  client_id INTEGER NOT NULL,
  event_id INTEGER NOT NULL,
  price_id INTEGER NOT NULL,
  FOREIGN KEY (client_id)
    REFERENCES client(client_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (event_id)
    REFERENCES event(event_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (price_id)
    REFERENCES price(price_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) engine=INNODB;